{
  parserClass               = "mobi.hsz.idea.gitignore.parser.GitignoreParser"

  extends                   = "com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix            = "Gitignore"
  psiImplClassSuffix        = "Impl"
  psiPackage                = "mobi.hsz.idea.gitignore.psi"
  psiImplPackage            = "mobi.hsz.idea.gitignore.psi.impl"
  psiImplUtilClass          = "mobi.hsz.idea.gitignore.psi.GitignorePsiUtil"

  elementTypeHolderClass    = "mobi.hsz.idea.gitignore.psi.GitignoreTypes"
  elementTypeClass          = "mobi.hsz.idea.gitignore.psi.GitignoreElementType"
  tokenTypeClass            = "mobi.hsz.idea.gitignore.psi.GitignoreTokenType"

  tokens = [
    private left NEGATION   = "!"
    HEADER                  = "regexp:###[^\r\n]*"
    SECTION                 = "regexp:##[^\r\n]*"
    COMMENT                 = "regexp:#[^\r\n]*"
    ENTRY_DIRECTORY         = "regexp:[^!#\s][\S ]*/"
    ENTRY_FILE              = "regexp:[^!#\s][\S ]*"
  ]
}

gitignoreFile       ::= item_*
private item_       ::= comment_ | entry_
private comment_    ::= HEADER | SECTION | COMMENT
private entry_      ::= NEGATED_ENTRY | ENTRY
NEGATED_ENTRY       ::= NEGATION (ENTRY_DIRECTORY | ENTRY_FILE) {extends="ENTRY"}
ENTRY               ::= ENTRY_DIRECTORY | ENTRY_FILE { methods=[getEntry] }